### PR TITLE
Validations and Error View

### PR DESCRIPTION
**Pull request by RaduSeba**
### Validations 
 - Now the List that pops-up when you add a marker is validated.
 - A message should be shown in red if you don t chose a name for a location or a type.
 - The same for editing a location.

### Error View 
- Before, as comments weren t implemented, the locations rended from the pod don t have the comments property. Now if you click a location from your pod or friends the app should crash and an error message should appear.

### Search functionality

- I think it s extra and we should focus on other things.
- As it didn't work I chose to remove the search bar from the app.

### CODE REVIEW

**Comment by juanmglzs** [comment]
Can some else check this? Because for me something weird is happening. It loads the locations but when i click on one, an errors is raised.

**Comment by juanmglzs** [comment]
This is what I am getting
https://user-images.githubusercontent.com/62023070/235451847-0d5dbc56-06eb-4e19-a90f-31193d385c60.mov

**Comment by FdezAriasSara** [comment]
> Can some else check this? Because for me something weird is happening. It loads the locations but when i click on one, an errors is raised.

Sebas created an error view , it arises when a location with different structure from the one in the pod is accessed , is that when you get the error?

I will check again anyways


btw: @juanmglzs Your last branch is finalintegration2 , right?

**Comment by juanmglzs** [comment]
https://user-images.githubusercontent.com/62023070/235452082-94e9e0b2-a451-4a65-bb1a-3f3424aea8fb.mov

**Comment by juanmglzs** [comment]
> Sebas created an error view , it arises when a location with different structure from the one in the pod is accessed , is that when you get the error?

No. It without doing anything. Login into the app, the locations are shown and when clicking in one this happens. 

> btw: @juanmglzs Your last branch is finalintegration2 , right?

No, it's finalintegration (without number) but I have made some changes that are not pushed yet cuz I'am still trying to test the img R/W. I can push it now but i wanted to test it with sebas' new changes (now the locations can have also a IMG and description) I wanted to do accept this PR to get this and test it all together

**Comment by FdezAriasSara** [comment]
> > Sebas created an error view , it arises when a location with different structure from the one in the pod is accessed , is that when you get the error?
> 
> No. It without doing anything. Login into the app, the locations are shown and when clicking in one this happens.
> 
> > btw: @juanmglzs Your last branch is finalintegration2 , right?
> 
> No, it's finalintegration (without number) but I have made some changes that are not pushed yet cuz I'am still trying to test the img R/W. I can push it now but i wanted to test it with sebas' new changes (now the locations can have also a IMG and description) I wanted to do accept this PR to get this and test it all together

oh ok i was going to have a look , but let me try and see if the same weird error happens to me, since yesterday i was literally unable to login into inrupt

**Comment by FdezAriasSara** [comment]
> > > Sebas created an error view , it arises when a location with different structure from the one in the pod is accessed , is that when you get the error?
> > 
> > 
> > No. It without doing anything. Login into the app, the locations are shown and when clicking in one this happens.
> > > btw: @juanmglzs Your last branch is finalintegration2 , right?
> > 
> > 
> > No, it's finalintegration (without number) but I have made some changes that are not pushed yet cuz I'am still trying to test the img R/W. I can push it now but i wanted to test it with sebas' new changes (now the locations can have also a IMG and description) I wanted to do accept this PR to get this and test it all together
> 
> oh ok i was going to have a look , but let me try and see if the same weird error happens to me, since yesterday i was literally unable to login into inrupt

@juanmglzs look, i get the error view, but in that location that is not consistent with the new  form locations have.

https://user-images.githubusercontent.com/79209608/235456717-96ff18ed-e22c-47a9-8889-5e84a2f34262.mp4

**Comment by RaduSeba** [comment]
> * [ ]  > > > Sebas created an error view , it arises when a location with different structure from the one in the pod is accessed , is that when you get the error?
> 
> > > No. It without doing anything. Login into the app, the locations are shown and when clicking in one this happens.
> > > > btw: @juanmglzs Your last branch is finalintegration2 , right?
> > > 
> > > 
> > > No, it's finalintegration (without number) but I have made some changes that are not pushed yet cuz I'am still trying to test the img R/W. I can push it now but i wanted to test it with sebas' new changes (now the locations can have also a IMG and description) I wanted to do accept this PR to get this and test it all together
> > 
> > 
> > oh ok i was going to have a look , but let me try and see if the same weird error happens to me, since yesterday i was literally unable to login into inrupt
> 
> @juanmglzs look, i get the error view, but in that location that is not consistent with the new form locations have., since it does not have the reviews.
> 
> I've just seen that you uploaded a video .. mm i will have a look at the place the error view is rendered add it the code.
> 
>  2023-05-01.15-14-25.mp4 
> edit: with a quick view, i see that Sebas uses a new component called MapErrorBoundary, and that logs the error in the console.
> 
> The error given:
> 
> image
> 
> this method @RaduSeba needs a try and catch image
> 
> in the try see if there are any comments, and in case they arent , im thinking that is not a good solution to stop the whole app ... so i would add a catch and make something like creating the comments in situ in case there arent, but i dont think an error view is ok there..
> 
> I see it better for things like a weird response error from inrupt or something, anything that actually prevents the app from working.


I added the try and catch but I think the problem is that the locations added from the pod don t have the comments filed, which I use to update the comments. If we add that than we shouldn't have errors.

**Comment by juanmglzs** [comment]
I've been working with a new SOLID POD and I didn't get any error while working with locations. I am still trying the review functionality.

**Pull request merged**
