### PR TITLE
Select provider Login and Logout 

### PR DESCRIPTION
**Pull request by FdezAriasSara**
PR for functionalities in  #86 

They are small things, but i will need them for testing.

image
 
Now the login redirects to the selected provider + the list shows the  selected one.
 
i added a go back button  to the logout dialogue and i adjusted the contents of it using a grid
image

also , the logout option does log out the user from the app.

### CODE REVIEW

**Comment by Batuhanbyr** [comment]
Hi sara, can u fix this? It's happen when the screen is small thank you

**Comment by FdezAriasSara** [comment]
> 
> 
> Hi sara, can u fix this? It's happen when the screen is small ıf u want ı can make it :) thank you

Of course, sorry! :) 

image
 

I changed few stuff, now it does work well in smaller windows and screens :) 

thank you !

**Comment by Batuhanbyr** [comment]
ıt's working so good! thanks

**Review by Batuhanbyr — APPROVED** [review]
i cloned it, and tested it and it's working good

**Pull request merged**
